name: Create And Push Image to Docker Hub

on:
  push:
    branches: ['main']

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate timestamp tag
        id: generate_tag
        run: |
          TIMESTAMP=$(date -u +"%Y%m%d%H%M%S")
          echo "Generated timestamp tag: $TIMESTAMP"
          echo "tag=$TIMESTAMP" >> "$GITHUB_OUTPUT"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          TAG=${{ steps.generate_tag.outputs.tag }}
          echo "Building Docker image with tag: $TAG"
          docker build -t suntzu12/lua-load-balancer:$TAG -f docker/nginx/Dockerfile docker/nginx

      - name: Push Docker Image
        run: |
          TAG=${{ steps.generate_tag.outputs.tag }}
          docker push suntzu12/lua-load-balancer:$TAG